//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrderList", ReplyAction="http://tempuri.org/IOrderService/GetOrderListResponse")]
        System.Collections.Generic.List<OrderManager.Model.Models.OM_Order> GetOrderList(string cipher, string userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrderList", ReplyAction="http://tempuri.org/IOrderService/GetOrderListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderManager.Model.Models.OM_Order>> GetOrderListAsync(string cipher, string userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrderItemList", ReplyAction="http://tempuri.org/IOrderService/GetOrderItemListResponse")]
        System.Collections.Generic.List<OrderManager.Model.Models.OM_OrderItem> GetOrderItemList(string cipher, string orderGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrderItemList", ReplyAction="http://tempuri.org/IOrderService/GetOrderItemListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderManager.Model.Models.OM_OrderItem>> GetOrderItemListAsync(string cipher, string orderGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : Web.OrderService.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<Web.OrderService.IOrderService>, Web.OrderService.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<OrderManager.Model.Models.OM_Order> GetOrderList(string cipher, string userGuid) {
            return base.Channel.GetOrderList(cipher, userGuid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderManager.Model.Models.OM_Order>> GetOrderListAsync(string cipher, string userGuid) {
            return base.Channel.GetOrderListAsync(cipher, userGuid);
        }
        
        public System.Collections.Generic.List<OrderManager.Model.Models.OM_OrderItem> GetOrderItemList(string cipher, string orderGuid) {
            return base.Channel.GetOrderItemList(cipher, orderGuid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderManager.Model.Models.OM_OrderItem>> GetOrderItemListAsync(string cipher, string orderGuid) {
            return base.Channel.GetOrderItemListAsync(cipher, orderGuid);
        }
    }
}
